### ISSUE TITLE
Makefile doesn't have all the dependencies?

### ISSUE THREAD

**Issue by teuben** [nbodyx/Nbody6ppGPU#10]
this is not a huge deal, but it would be nice if you edit a file like src/Main/input.F
 that the command "make" would build it. But in my case I see

    touch src/Main/input.F
    make
    make: './build/nbody6++.avx' is up to date.

so to fix this I had to

    rm ./build/nbody6++.avx
    make

after which I got a new executable.

Reason of my tinkering is a NEMO frontend to nbody6++ that I just about finished. There is no man page for this yet, but to give you an idea, it will be very similar to the one described in https://teuben.github.io/nemo/man_html/runbody1.1.html

thank you for maintaining nbody6++, it's been very easy to compile and run (but brittle too, as I'm getting some of those CALCULATIONS HALTED cases.

**Comment by lwang-astro** [comment]
Thank you for the comment. Currently there are two Makefile to control the compiling. The objects dependence are written in the inner Makefile in build/. Thus if objects are modified but the compiled binaries still exist, the major Makefile cannot identify the change. Once you delete the compiled binaries and make again, it can identify the change of subroutines. Right now I don't have a good idea how to make the objects dependence transparent in the major Makefile.
