### ISSUE TITLE
period calculation in start.F

### ISSUE THREAD

**Issue by bilibilihuangyifan** [nbodyx/Nbody6ppGPU#11]
https://github.com/nbodyx/Nbody6ppGPU/blob/4b3555b58a0c58dbf3ab839a38f3cddb484d37c7/src/Main/start.F#L173
This line is correct only when the initial eccentricity is zero.
For an arbitrary orbit, please use 
https://github.com/nbodyx/Nbody6ppGPU/blob/4b3555b58a0c58dbf3ab839a38f3cddb484d37c7/src/Main/kspreg.F#L170
https://github.com/nbodyx/Nbody6ppGPU/blob/4b3555b58a0c58dbf3ab839a38f3cddb484d37c7/src/Main/kspreg.F#L182
https://github.com/nbodyx/Nbody6ppGPU/blob/4b3555b58a0c58dbf3ab839a38f3cddb484d37c7/src/Main/kspreg.F#L211

**Comment by lwang-astro** [comment]
Thank you for pointing this issue out. I usually did not check the initial output of the binary periods. But it can be fixed. I have done it in the newest commit.
