### ISSUE TITLE
configure problem on mpi

### ISSUE THREAD

**Issue by kaiwu-astro** [nbodyx/Nbody6ppGPU#12]
Hi,

There's a problem when I run `./configure` with MPI (without GPU). In the configure log (see here [config.zip](https://github.com/nbodyx/Nbody6ppGPU/files/3033660/config.zip)),
line 148 gives: `configure:2958: gfortran -c -g  conftest.f >&5`
line 154 gives: `configure:3293: none -c  -O3  -fPIC  conftest.f >&5`

I tested `gfortran -c  -O3  -fPIC  conftest.f` with a blank conftest.f and it didn't give an error. I don't understand why _gfortran_ was changed to _none_ while I run `./configure`. Is it a bug?

This does not happen when I use `--disable-mpi` (without GPU).

Thanks!
Kai

**Comment by lwang-astro** [comment]
Did you have mpif77 installed in your system. If you don't use --disable-mpi, it assumes you have mpif77 compiler.

**Comment by kaiwu-astro** [comment]
> Did you have mpif77 installed in your system. If you don't use --disable-mpi, it assumes you have mpif77 compiler.

I just realized that I didn't install mpif77, and the problem is solved after I have it. 

Thanks :)
