### ISSUE TITLE
does nbody6++ run on Xeon?

### ISSUE THREAD

**Issue by teuben** [nbodyx/Nbody6ppGPU#13]
I've been able to compile and run nbody6++ just fine, on simple machine, no gpu, no mpi:

          ./configure --disable-gpu --disable-mpi 
          make
after which you can run build/nbody6++.avx

When I build it on i7 based intel, or xeon based intel, it runs fine on i7, but either way, both of them fail on xeon for me.

             ALPHAS = 2.30  BODY1 = 10.0  BODYN = 0.20 ZMASS = 1.00000E+03 NBIN0 =    0 NHI0 =    0 ZMET = 0.0010 EPOCH0 = 0.00
Illegal instruction (core dumped)

**Comment by teuben** [comment]
I'll give myself a partial answer to this:
I was using an older Scientific Linux 6.7 version, but on RedHat 7.6 the Xeon compiled version ran find on Xeon, but not on an i7.  Perhaps the compile flags are too strict for the CPU, but for my department we have too many types of machines (2) and cpu's (2).

**Comment by lwang-astro** [comment]
The illegal instruction may indicate the Xeon CPU do not support AVX. If the configure work correctly in the Xeon machine, it would provide a warning if the AVX is not supported by the local CPU type. In such case, --enable-simd=sse can be used instead

**Comment by teuben** [comment]
thank you so much!     indeed I now see that warning in configure:
         configure:      Using SIMD:     avx
         configure: WARNING:       SIMD option used now is not supported in current CPU
and with sse it works on both i7/xeon.

**Comment by teuben** [comment]
Just for reference, this is how I install nbody6++ in NEMO:
https://github.com/teuben/nemo/blob/master/usr/aarseth/Makefile
