### ISSUE TITLE
Suspicious indexing in start.F

### ISSUE THREAD

**Issue by mdelorme** [nbodyx/Nbody6ppGPU#14]
Hi !

On line 169 of start.F we can read :

https://github.com/nbodyx/Nbody6ppGPU/blob/381d0433c500edf126e9aa59acf3695cdf700528/src/Main/start.F#L169-L170

Are the two different set of indices (ICOMP/I1; JCOMP/I2) wanted ? 

This part crashes when we run it with the sample N10K_B1k.input, and works when we replace I1/I2 with ICOMP/JCOMP.

**Comment by lwang-astro** [comment]
Thank you for pointing this bug. This is introduced from recent update.
I have fixed in the new version
