### ISSUE TITLE
Pure CPU version stuck in infinite loop

### ISSUE THREAD

**Issue by mdelorme** [nbodyx/Nbody6ppGPU#16]
Hi, 

One of our interns is trying to run Nbody6++ with in a pure CPU settings and the code freezes completely after a while. I don't know if you intend to keep some support for pure CPU runs, but just in case I thought I should let you know.

Here's the input :

```
1 5000000.0 50.0000000000000000 40 40 0
18006 1 10 95986 268 1 10
0.02 0.02 0.14631448 1.00000000 1.00000000 1594.86886621 0.000056 2.6054950556736229 0.5554379421168758
0 2 1 0 1 0 5 0 3 2
0 1 0 3 2 0 0 0 3 6
0 10 2 0 1 2 1 0 0 1
1 0 3 2 1 0 0 2 0 0
0 0 0 0 0 2 -3 0 0 0
0.000007 0.000382 0.2 1.0 0.000001 0.001 0.125
2.350000 150.00000000 0.08000000 0 0 0.00010000 0.00000000 1.00000000
0.50 0.0 0.0 0.00000
1.405920e+10 0.387300 8.560800e+10 5.317800 0.250000 1.070680e+11 12.000000 0.000000 1.000000 1.000000
8.500000 0.000000 0.000000 0.000000 220.000000 0.000000
0.00 0.00 0.00 0.00
```

**Comment by lwang-astro** [comment]
Hi,

 

The pure CPU run should works. 

Your input number of star is a bit large for a CPU run. How many CPU cores did you use? Which type of CPU? Did you switch on AVX/SSE features?

Besides, without the output information, it is difficult to know the reason for the problem.

 

Bests.

Long

 

发件人: Maxime Delorme <notifications@github.com> 
发送时间: 2019年7月31日 0:14
收件人: nbodyx/Nbody6ppGPU <Nbody6ppGPU@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [nbodyx/Nbody6ppGPU] Pure CPU version stuck in infinite loop (#16)

 

Hi,

One of our interns is trying to run Nbody6++ with in a pure CPU settings and the code freezes completely after a while. I don't know if you intend to keep some support for pure CPU runs, but just in case I thought I should let you know.

Here's the input :

1 5000000.0 50.0000000000000000 40 40 0
18006 1 10 95986 268 1 10
0.02 0.02 0.14631448 1.00000000 1.00000000 1594.86886621 0.000056 2.6054950556736229 0.5554379421168758
0 2 1 0 1 0 5 0 3 2
0 1 0 3 2 0 0 0 3 6
0 10 2 0 1 2 1 0 0 1
1 0 3 2 1 0 0 2 0 0
0 0 0 0 0 2 -3 0 0 0
0.000007 0.000382 0.2 1.0 0.000001 0.001 0.125
2.350000 150.00000000 0.08000000 0 0 0.00010000 0.00000000 1.00000000
0.50 0.0 0.0 0.00000
1.405920e+10 0.387300 8.560800e+10 5.317800 0.250000 1.070680e+11 12.000000 0.000000 1.000000 1.000000
8.500000 0.000000 0.000000 0.000000 220.000000 0.000000
0.00 0.00 0.00 0.00

**Comment by mdelorme** [comment]
Hey, 

Ok after further investigation it was a poor configuration on our part. I remember having another problem with CPU runs (with ~4k particles) but couldn't reproduce this anymore.

Sorry for the inconvenience ^^.
