### ISSUE TITLE
How to increase the accuracy?

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#17]
Hello,
I have been trying to model dense stellar systems accurately. I am trying to achieve a maximum relative energy error of the order of 1E-3. However, in my simulations, I observe that the energy error often goes over that and the simulation restarts and then stops. What parameters should I change to increase the accuracy? I started with ETAI = 0.01 and ETAR = 0.02

**Comment by lwang-astro** [comment]
Decrease ETAR works better for dense cluster.
A safe but low-performance ETAR = 0.005. 
You can first try to use ETAR= 0.01. 

On the other hand, if there are binaries, the RMIN and DTMIN for KS and Chain regularization are also important for energy conservation.
