### ISSUE TITLE
Collisions and RMIN, DTMIN

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#20]
Hello,
I was running simulations on a dense stellar system without primordial binaries. I noticed that when I increased DTMIN and RMIN, more collisions were detected compared to when DTMIN and RMIN was decreased. Any reason why that might be happening? I am currently using DTMIN, RMIN = 1.0E-6. For modeling dense systems, does decreasing the DTMIN, RMIN increase accuracy? 

Thank you for your help.

**Comment by lwang-astro** [comment]
The collision check is only done in the KS/Chain regularization. When DTMIN and RMIN are two small. Some high eccentric and hyperbolic collisions may be missed. This may explain what you have found.
