### ISSUE TITLE
Disabling Regularization entirely

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#21]
Hello,
Is there any way to completely disable KS regularization inside NBODY6? 

Thank you.

**Comment by lwang-astro** [comment]
You can set very small RMIN and DTMIN to disable KS

**Comment by dipto4** [comment]
Thank you for the info. I set RMIN and DTMIN to 1.0E-30 but I still find binaries being produced in the output files. Is there any way to change this?

Thank you.

**Comment by lwang-astro** [comment]
If there is no output of NEW KS in the main output. Then it is suppressed. In the snapshot files, the binary is detected by the Kepler orbital element. This is independent of KS regularization.
