### ISSUE TITLE
Sudden Increases in RSCALE

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#22]
Hello,
I am modeling a very dense star cluster. Over an ensemble of simulations, I noticed that in some simulations, RSCALE increases really suddenly over a really short timescale (<< TRH). DE stays below tolerance parameter. Any reason why such jumps may be happening? Is the code producing something unphysical?

**Comment by lwang-astro** [comment]
If it happens in the early time with stellar evolution (<100 Myr). The increase may be due to the strong stellar wind, formation of NSs and BHs. A large amount of mass is lost in a short time, thus the RSCALE can increase.

**Comment by dipto4** [comment]
Stellar evolution was not enabled in my simulation. Can a large number of escapers lead to an increase in RSCALE?

**Comment by lwang-astro** [comment]
If there is a tidal field and a large number of escapers exist, the system may lose equilibrium. See http://adsabs.harvard.edu/abs/1995MNRAS.276..206F .
Then the cluster can dissolve fast.
