### ISSUE TITLE
new time step mloss.f

### ISSUE THREAD

**Issue by rdominguez89** [nbodyx/Nbody6ppGPU#25]
My simulations do not progress any more when mloss.f redefine 
STEP(IMAX) and STEPR(IMAX).
I am using KZ(19)=1.
In mdot.f ( KZ(19)>=3 ) the reduction of the time step is commented.
Should it be enough commenting this in mloss.f too?

**Comment by lwang-astro** [comment]
Now KZ(19)=1 is not maintained any more for NBODY6 and NBODY6++. SSE/BSE is currently the only working stellar evolution package. If there is no special reason, it is suggested to always use KZ(19)>=3.
