### ISSUE TITLE
Segmentation Fault while running simulation

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#26]
Hello,
I was running long simulation with 4k particles and I saw that some of my simulations crashed after a few hours with the following error:
`Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`
I could not find a backtrace. Any ideas on what might be causing this?

Thanks.

**Comment by dipto4** [comment]
Just some more information regarding the issue. I was running the CPU version with 24 threads. The segmentation fault is triggered whenever I get the following in the output:
`Warning!: Regular step jump!`

**Comment by lwang-astro** [comment]
How many particles are there when the error appear? If the particle number is very small (e.g. <50). The code may not work well. Besides, can you reproduce the error by restarting the simulation from last dump file?

**Comment by dipto4** [comment]
4k particles were present when error appeared. The error is reproduced by restarting the simulation from the last dump file. The error disappears when AVX is disabled and simulation is started from the last dump file. Any idea why this might be happening?

Thanks.

**Comment by dipto4** [comment]
Hello,
Running with GDB, I found the source of the segmentation fault from backtrace. It seems like the following line is causing issues:
`src/Main/intgrt.F:591`

Any ideas on what it might be?

Thank you.

**Comment by dipto4** [comment]
Sorry for so many comments. Upon running the same simulation with one thread, I get the following backtrace:
```
#0  0x000055555575501d in regcor_gpu (i=1004, xi=..., xidot=..., freg=..., fdr=..., nlist=...) at ../src/Main/regcor_gpu.F:415
#1  0x0000555555752e5c in calc_reg_on_gpu (ireg=<error reading variable: value requires 524288 bytes, which is more than max-value-size>, istart=1, iend=8192)
    at ../src/Main/util_gpu.F:175
#2  0x000055555560213e in intgrt () at ../src/Main/intgrt.F:944
#3  0x0000555555557a4d in nbody6 () at ../src/Main/nbody6.F:196
#4  0x00005555555581d0 in main (argc=1, argv=0x7fffffffdc68) at ../src/Main/nbody6.F:271
#5  0x0000155554398b97 in __libc_start_main (main=0x555555558157 <main>, argc=1, argv=0x7fffffffd868, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffd858) at ../csu/libc-start.c:310
#6  0x0000555555555eca in _start ()
```

Hope this helps. In this simulation I was using 8192 particles.

**Comment by lwang-astro** [comment]
Looks like a memory leak problem. From the current information it is hard to identify the issue. Do you have any other special event from the output. I have not seen such problem before. It may relate to the special initial condition that you are simulating.

**Comment by dipto4** [comment]
I don't know how this information might help but the issue is not encountered when using the GPU version of the code. It only happens in the pure CPU version of the code.

**Comment by dipto4** [comment]
I am attaching the initial conditions and the input files that I used, if that helps.

Thank you.
[ic.zip](https://github.com/nbodyx/Nbody6ppGPU/files/4689857/ic.zip)

**Comment by lwang-astro** [comment]
Sorry for long time no reply. The rs0 in your input parameter is too large. The neighbor number overflow and exceeding the memory limit of GPU.
