### ISSUE TITLE
Compilation problem in kick.F

### ISSUE THREAD

**Issue by mdelorme** [nbodyx/Nbody6ppGPU#27]
Hey, 

I just pulled the last version of the code and now it does not compile anymore. For some reason the compilers (ifortran or gfortran) are thinking that there's an unclosed if block in kick.F. 

Here's the message I get in ifortran :

```
../src/Main/kick.F(167): warning #6371: A jump into a block from outside the block may have occurred.   [30]
     &        (KW.EQ.12.AND.KZ(25).NE.2)) GO TO 30
------------------------------------------------^
../src/Main/kick.F(289): error #6321: An unterminated block exists.
      IF (BHFLAG.GT.1) THEN
^
../src/Main/kick.F(233): error #6321: An unterminated block exists.
      ELSE
^
compilation aborted for ../src/Main/kick.F (code 1)
```

And the one I get in gfortran : 

```
430 |       END
      |         1
Error: END IF statement expected at (1)
```

I had a look but couldn't find any unclosed block in the code ...

**Comment by lwang-astro** [comment]
Thanks for report. The last update of kick.F introduce a mistake. Now it is fixed.

**Comment by mdelorme** [comment]
Great ! Thanks for the swift answer ! It compiles perfectly now :)
