### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by emmeDG** [nbodyx/Nbody6ppGPU#29]
Today I was trying to install Nbody6++ but I am facing some issues. First of all, I tried the simplest procedure using `./configure` but this raises the following issue with the fortran compiler: 
```
configure: error: compiler option -fPIC/-fpic not avaiable, please use GNU or Intel Fortran compiler
See `config.log' for more details
```
The same happens if I use `./configure --prefix=[MY_PATH]`, but it vanishes if I add the options `--disable-mpi --disable-openmp --disable-gpu` (basically, I want to start using it without GPU or MPI support).

Also, if I specify my installation path I don't get the folders `bin`, `doc`, `include` and `lib` in it but only `bin` and `share`.

Then, if I complete the installation using 
```
./configure --prefix=[MY_PATH]--disable-mpi --disable-openmp --disable-gpu
make
make install
```
and try to run the code using one of the sample input files:
```
cd MY_PATH/bin
./nbody6++ /MY_HOME/Nbody6ppGPU/samples/N16k.input /MY_HOME/trial.out &
```
The code apparently fails to work. It has not output or nothing that allows me to check if something is running or not and no output file is created.

What causes the issue?

Please note that I tried this same procedure on two different machines with fortran an C compiler correctly installed, but the result is the same.

**Comment by dhruvmalhtra** [comment]
I am having the same problem. Did you get it resolved?
