### ISSUE TITLE
Problems starting the code

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#7]
Hello,
I was trying to run the NBODY6++GPU code with one of the sample .input files provided. However, when I ran it, the code did not do anything. I used the following command to start the code
`./nbody6++.gpu.avx.mpi N16k.input output`. The code built without any errors. Could you point out if I am doing anything wrong?

Thank you.

**Comment by FrancescoFlammini** [comment]
Hi! The input part should be like <N16k.input>. 

Bye

**Comment by dipto4** [comment]
Thank you!
