### ISSUE TITLE
Question regarding collisions

### ISSUE THREAD

**Issue by dipto4** [nbodyx/Nbody6ppGPU#8]
Hi!
I am getting started with NBODY6++ and I was wondering if it detects collisions by default. If not, how do I enable it? How are the collisions resolved (if I am not using stellar evolution)?

Thank you so much!

**Comment by lwang-astro** [comment]
If you switched on stellar evolution KZ(19)=3 and tidal circularization KZ(27)=1 option. The collision happens.

**Comment by dipto4** [comment]
So if KZ(19) = 0, it will not detect collisions?

**Comment by lwang-astro** [comment]
Yes, if no stellar evolution, stars are treated as point mass particles

**Comment by dipto4** [comment]
Thank you so much!
